# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'inicio_sesion.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(308, 203)
        MainWindow.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.693, y1:0.228591, x2:0.909, y2:0.0565455, stop:0 rgba(16, 60, 84, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.boton_iniciar_sesion = QPushButton(self.centralwidget)
        self.boton_iniciar_sesion.setObjectName(u"boton_iniciar_sesion")
        self.boton_iniciar_sesion.setGeometry(QRect(80, 120, 201, 51))
        palette = QPalette()
        brush = QBrush(QColor(0, 0, 0, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        gradient = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient.setSpread(QGradient.Spread.PadSpread)
        gradient.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient.setColorAt(0, QColor(16, 60, 84, 255))
        gradient.setColorAt(1, QColor(255, 255, 255, 255))
        brush1 = QBrush(gradient)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        brush2 = QBrush(QColor(255, 255, 255, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush2)
        gradient1 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient1.setSpread(QGradient.Spread.PadSpread)
        gradient1.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient1.setColorAt(0, QColor(16, 60, 84, 255))
        gradient1.setColorAt(1, QColor(255, 255, 255, 255))
        brush3 = QBrush(gradient1)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush3)
        gradient2 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient2.setSpread(QGradient.Spread.PadSpread)
        gradient2.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient2.setColorAt(0, QColor(16, 60, 84, 255))
        gradient2.setColorAt(1, QColor(255, 255, 255, 255))
        brush4 = QBrush(gradient2)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush4)
        brush5 = QBrush(QColor(96, 47, 255, 255))
        brush5.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush5)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        gradient3 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient3.setSpread(QGradient.Spread.PadSpread)
        gradient3.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient3.setColorAt(0, QColor(16, 60, 84, 255))
        gradient3.setColorAt(1, QColor(255, 255, 255, 255))
        brush6 = QBrush(gradient3)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush6)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush2)
        gradient4 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient4.setSpread(QGradient.Spread.PadSpread)
        gradient4.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient4.setColorAt(0, QColor(16, 60, 84, 255))
        gradient4.setColorAt(1, QColor(255, 255, 255, 255))
        brush7 = QBrush(gradient4)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush7)
        gradient5 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient5.setSpread(QGradient.Spread.PadSpread)
        gradient5.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient5.setColorAt(0, QColor(16, 60, 84, 255))
        gradient5.setColorAt(1, QColor(255, 255, 255, 255))
        brush8 = QBrush(gradient5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush8)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush5)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush)
        gradient6 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient6.setSpread(QGradient.Spread.PadSpread)
        gradient6.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient6.setColorAt(0, QColor(16, 60, 84, 255))
        gradient6.setColorAt(1, QColor(255, 255, 255, 255))
        brush9 = QBrush(gradient6)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush9)
        gradient7 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient7.setSpread(QGradient.Spread.PadSpread)
        gradient7.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient7.setColorAt(0, QColor(16, 60, 84, 255))
        gradient7.setColorAt(1, QColor(255, 255, 255, 255))
        brush10 = QBrush(gradient7)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush10)
        gradient8 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient8.setSpread(QGradient.Spread.PadSpread)
        gradient8.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient8.setColorAt(0, QColor(16, 60, 84, 255))
        gradient8.setColorAt(1, QColor(255, 255, 255, 255))
        brush11 = QBrush(gradient8)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush11)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Highlight, brush5)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush)
        self.boton_iniciar_sesion.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        self.boton_iniciar_sesion.setFont(font)
        self.boton_iniciar_sesion.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.boton_iniciar_sesion.setFocusPolicy(Qt.FocusPolicy.StrongFocus)
        self.boton_iniciar_sesion.setContextMenuPolicy(Qt.ContextMenuPolicy.ActionsContextMenu)
        self.boton_iniciar_sesion.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.boton_iniciar_sesion.setAutoFillBackground(False)
        self.boton_iniciar_sesion.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.693, y1:0.228591, x2:0.909, y2:0.0565455, stop:0 rgba(16, 60, 84, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_contrasena = QLabel(self.centralwidget)
        self.label_contrasena.setObjectName(u"label_contrasena")
        self.label_contrasena.setGeometry(QRect(60, 60, 95, 21))
        palette1 = QPalette()
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        gradient9 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient9.setSpread(QGradient.Spread.PadSpread)
        gradient9.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient9.setColorAt(0, QColor(16, 60, 84, 255))
        gradient9.setColorAt(1, QColor(255, 255, 255, 255))
        brush12 = QBrush(gradient9)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush12)
        gradient10 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient10.setSpread(QGradient.Spread.PadSpread)
        gradient10.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient10.setColorAt(0, QColor(16, 60, 84, 255))
        gradient10.setColorAt(1, QColor(255, 255, 255, 255))
        brush13 = QBrush(gradient10)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush13)
        gradient11 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient11.setSpread(QGradient.Spread.PadSpread)
        gradient11.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient11.setColorAt(0, QColor(16, 60, 84, 255))
        gradient11.setColorAt(1, QColor(255, 255, 255, 255))
        brush14 = QBrush(gradient11)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush14)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush5)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        gradient12 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient12.setSpread(QGradient.Spread.PadSpread)
        gradient12.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient12.setColorAt(0, QColor(16, 60, 84, 255))
        gradient12.setColorAt(1, QColor(255, 255, 255, 255))
        brush15 = QBrush(gradient12)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush15)
        gradient13 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient13.setSpread(QGradient.Spread.PadSpread)
        gradient13.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient13.setColorAt(0, QColor(16, 60, 84, 255))
        gradient13.setColorAt(1, QColor(255, 255, 255, 255))
        brush16 = QBrush(gradient13)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush16)
        gradient14 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient14.setSpread(QGradient.Spread.PadSpread)
        gradient14.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient14.setColorAt(0, QColor(16, 60, 84, 255))
        gradient14.setColorAt(1, QColor(255, 255, 255, 255))
        brush17 = QBrush(gradient14)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush17)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush5)
        gradient15 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient15.setSpread(QGradient.Spread.PadSpread)
        gradient15.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient15.setColorAt(0, QColor(16, 60, 84, 255))
        gradient15.setColorAt(1, QColor(255, 255, 255, 255))
        brush18 = QBrush(gradient15)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush18)
        gradient16 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient16.setSpread(QGradient.Spread.PadSpread)
        gradient16.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient16.setColorAt(0, QColor(16, 60, 84, 255))
        gradient16.setColorAt(1, QColor(255, 255, 255, 255))
        brush19 = QBrush(gradient16)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush19)
        gradient17 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient17.setSpread(QGradient.Spread.PadSpread)
        gradient17.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient17.setColorAt(0, QColor(16, 60, 84, 255))
        gradient17.setColorAt(1, QColor(255, 255, 255, 255))
        brush20 = QBrush(gradient17)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush20)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Highlight, brush5)
        self.label_contrasena.setPalette(palette1)
        font1 = QFont()
        font1.setFamilies([u"Franklin Gothic"])
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setItalic(True)
        self.label_contrasena.setFont(font1)
        self.label_contrasena.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.label_contrasena.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.693, y1:0.228591, x2:0.909, y2:0.0565455, stop:0 rgba(16, 60, 84, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_contrasena.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_contrasena.setIndent(0)
        self.entry_contrasena = QLineEdit(self.centralwidget)
        self.entry_contrasena.setObjectName(u"entry_contrasena")
        self.entry_contrasena.setGeometry(QRect(180, 60, 116, 22))
        palette2 = QPalette()
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush21 = QBrush(QColor(217, 217, 217, 255))
        brush21.setStyle(Qt.BrushStyle.SolidPattern)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush21)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush21)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush21)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush5)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.HighlightedText, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush21)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush21)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush21)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush5)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.HighlightedText, brush)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush21)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush21)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush21)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Highlight, brush5)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.HighlightedText, brush)
        self.entry_contrasena.setPalette(palette2)
        font2 = QFont()
        font2.setBold(True)
        self.entry_contrasena.setFont(font2)
        self.entry_contrasena.setStyleSheet(u"background-color: rgb(217, 217, 217);")
        self.entry_contrasena.setEchoMode(QLineEdit.EchoMode.Password)
        self.label_usuario = QLabel(self.centralwidget)
        self.label_usuario.setObjectName(u"label_usuario")
        self.label_usuario.setGeometry(QRect(30, 20, 63, 21))
        palette3 = QPalette()
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        gradient18 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient18.setSpread(QGradient.Spread.PadSpread)
        gradient18.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient18.setColorAt(0, QColor(16, 60, 84, 255))
        gradient18.setColorAt(1, QColor(255, 255, 255, 255))
        brush22 = QBrush(gradient18)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush22)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush2)
        gradient19 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient19.setSpread(QGradient.Spread.PadSpread)
        gradient19.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient19.setColorAt(0, QColor(16, 60, 84, 255))
        gradient19.setColorAt(1, QColor(255, 255, 255, 255))
        brush23 = QBrush(gradient19)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush23)
        gradient20 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient20.setSpread(QGradient.Spread.PadSpread)
        gradient20.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient20.setColorAt(0, QColor(16, 60, 84, 255))
        gradient20.setColorAt(1, QColor(255, 255, 255, 255))
        brush24 = QBrush(gradient20)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush24)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush5)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        gradient21 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient21.setSpread(QGradient.Spread.PadSpread)
        gradient21.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient21.setColorAt(0, QColor(16, 60, 84, 255))
        gradient21.setColorAt(1, QColor(255, 255, 255, 255))
        brush25 = QBrush(gradient21)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush25)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush2)
        gradient22 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient22.setSpread(QGradient.Spread.PadSpread)
        gradient22.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient22.setColorAt(0, QColor(16, 60, 84, 255))
        gradient22.setColorAt(1, QColor(255, 255, 255, 255))
        brush26 = QBrush(gradient22)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush26)
        gradient23 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient23.setSpread(QGradient.Spread.PadSpread)
        gradient23.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient23.setColorAt(0, QColor(16, 60, 84, 255))
        gradient23.setColorAt(1, QColor(255, 255, 255, 255))
        brush27 = QBrush(gradient23)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush27)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush5)
        gradient24 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient24.setSpread(QGradient.Spread.PadSpread)
        gradient24.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient24.setColorAt(0, QColor(16, 60, 84, 255))
        gradient24.setColorAt(1, QColor(255, 255, 255, 255))
        brush28 = QBrush(gradient24)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush28)
        gradient25 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient25.setSpread(QGradient.Spread.PadSpread)
        gradient25.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient25.setColorAt(0, QColor(16, 60, 84, 255))
        gradient25.setColorAt(1, QColor(255, 255, 255, 255))
        brush29 = QBrush(gradient25)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush29)
        gradient26 = QLinearGradient(0.693, 0.228591, 0.909, 0.0565455)
        gradient26.setSpread(QGradient.Spread.PadSpread)
        gradient26.setCoordinateMode(QGradient.CoordinateMode.ObjectBoundingMode)
        gradient26.setColorAt(0, QColor(16, 60, 84, 255))
        gradient26.setColorAt(1, QColor(255, 255, 255, 255))
        brush30 = QBrush(gradient26)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush30)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Highlight, brush5)
        self.label_usuario.setPalette(palette3)
        self.label_usuario.setFont(font1)
        self.label_usuario.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.label_usuario.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0.693, y1:0.228591, x2:0.909, y2:0.0565455, stop:0 rgba(16, 60, 84, 255), stop:1 rgba(255, 255, 255, 255));")
        self.label_usuario.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.entry_usuario = QLineEdit(self.centralwidget)
        self.entry_usuario.setObjectName(u"entry_usuario")
        self.entry_usuario.setGeometry(QRect(120, 20, 116, 22))
        palette4 = QPalette()
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Button, brush21)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Light, brush2)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Midlight, brush2)
        brush31 = QBrush(QColor(127, 127, 127, 255))
        brush31.setStyle(Qt.BrushStyle.SolidPattern)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Dark, brush31)
        brush32 = QBrush(QColor(170, 170, 170, 255))
        brush32.setStyle(Qt.BrushStyle.SolidPattern)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Mid, brush32)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.BrightText, brush2)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ButtonText, brush)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Base, brush21)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush21)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Shadow, brush)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Highlight, brush5)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.AlternateBase, brush2)
        brush33 = QBrush(QColor(255, 255, 220, 255))
        brush33.setStyle(Qt.BrushStyle.SolidPattern)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipBase, brush33)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.ToolTipText, brush)
        brush34 = QBrush(QColor(0, 0, 0, 127))
        brush34.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.PlaceholderText, brush34)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Accent, brush2)
#endif
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Button, brush21)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Light, brush2)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Midlight, brush2)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Dark, brush31)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Mid, brush32)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.BrightText, brush2)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ButtonText, brush)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Base, brush21)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush21)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Shadow, brush)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Highlight, brush5)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.AlternateBase, brush2)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipBase, brush33)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.ToolTipText, brush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.PlaceholderText, brush34)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Accent, brush2)
#endif
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush31)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Button, brush21)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Light, brush2)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Midlight, brush2)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Dark, brush31)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Mid, brush32)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush31)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.BrightText, brush2)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ButtonText, brush31)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush21)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush21)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Shadow, brush)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Highlight, brush5)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.AlternateBase, brush2)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipBase, brush33)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.ToolTipText, brush)
        brush35 = QBrush(QColor(127, 127, 127, 127))
        brush35.setStyle(Qt.BrushStyle.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.PlaceholderText, brush35)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(6, 6, 0)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Accent, brush2)
#endif
        self.entry_usuario.setPalette(palette4)
        font3 = QFont()
        font3.setPointSize(9)
        font3.setBold(True)
        self.entry_usuario.setFont(font3)
        self.entry_usuario.setStyleSheet(u"background-color: rgb(217, 217, 217);")
        MainWindow.setCentralWidget(self.centralwidget)

        self.label_usuario.raise_()
        self.entry_usuario.raise_()
        self.label_contrasena.raise_()
        self.entry_contrasena.raise_()
        self.boton_iniciar_sesion.raise_()


        self.retranslateUi(MainWindow)
        self.entry_usuario.setFocus()
        self.entry_usuario.returnPressed.connect(self.entry_contrasena.setFocus)
        self.entry_contrasena.returnPressed.connect(self.boton_iniciar_sesion.setFocus)

        self.boton_iniciar_sesion.setDefault(True)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.boton_iniciar_sesion.setText(QCoreApplication.translate("MainWindow", u"Iniciar Sesi\u00f3n: D A T C O R R ", None))
        self.label_contrasena.setText(QCoreApplication.translate("MainWindow", u"Contrase\u00f1a", None))
        self.entry_contrasena.setText("")
        self.label_usuario.setText(QCoreApplication.translate("MainWindow", u"Usuario", None))
    # retranslateUi

